plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.6
  Exclude:
    - .git/**/*
    - spec/coveralls/fixtures/**/*
    - tmp/**/*
    - vendor/**/*

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 26.31
  Exclude:
    - 'lib/coveralls/configuration.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/coveralls/configuration.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/coveralls/configuration.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/coveralls/configuration.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'lib/coveralls/configuration.rb'
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
